import type { Project } from '../types/project';

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: '모바일 반응형 업무 관리 웹앱 출시',
    description: '어디서나 접속하여 프로젝트 진척도와 업무 일지를 실시간 관리하는 웹 대시보드 구축 및 Netlify 배포',
    category: '개발',
    priority: 'urgent',
    status: 'in-progress',
    startDate: '2026-10-01',
    endDate: '2026-10-15',
    autoCalculateProgress: true,
    manualProgress: 60,
    tags: ['React', 'Vite', 'Netlify', 'Tailwind'],
    tasks: [
      { id: 't1-1', title: '요구사항 정의 및 아키텍처 설계', completed: true, dueDate: '2026-10-03' },
      { id: 't1-2', title: 'React + TypeScript + Tailwind 환경 셋업', completed: true, dueDate: '2026-10-05' },
      { id: 't1-3', title: '대시보드 통계 및 프로젝트 카드 컴포넌트 개발', completed: true, dueDate: '2026-10-08' },
      { id: 't1-4', title: '칸반 보드 및 타임라인 간트 뷰 구현', completed: false, dueDate: '2026-10-11' },
      { id: 't1-5', title: '업무 일지 기록 및 실시간 진척도 연동', completed: false, dueDate: '2026-10-13' },
      { id: 't1-6', title: 'GitHub 저장소 푸시 및 Netlify 배포 완료', completed: false, dueDate: '2026-10-15' },
    ],
    logs: [
      {
        id: 'log-1-1',
        date: '2026-10-02',
        category: 'meeting',
        content: '프로젝트 범위 확정: 반응형 모바일 지원, 칸반 및 타임라인 뷰 제공 결정',
        author: '나',
      },
      {
        id: 'log-1-2',
        date: '2026-10-05',
        category: 'progress',
        content: 'Vite 기반 React 프로젝트 셋업 완료 및 Tailwind 디자인 시스템 적용 완료',
        author: '나',
      },
      {
        id: 'log-1-3',
        date: '2026-10-07',
        category: 'note',
        content: '로컬 스토리지 자동 저장 및 JSON 백업/복원 기능 추가 완료',
        author: '나',
      },
    ],
    createdAt: '2026-10-01T09:00:00.000Z',
    updatedAt: '2026-10-07T11:00:00.000Z',
  },
  {
    id: 'proj-2',
    title: '신제품 품목허가 신청 및 규격 인증 승인',
    description: '신제품 출시를 위한 기술문서 작성, 공인 시험성적서 발급 및 식약처/규제기관 인허가 승인 취득',
    category: '인허가',
    priority: 'high',
    status: 'planned',
    startDate: '2026-10-10',
    endDate: '2026-11-15',
    autoCalculateProgress: true,
    manualProgress: 25,
    tags: ['인허가', '식약처', '규격인증', '기술문서'],
    tasks: [
      { id: 't2-1', title: '기술문서(STED) 및 제품 설명서 초안 작성', completed: true, dueDate: '2026-10-15' },
      { id: 't2-2', title: '공인 시험기관 안전성/유효성 시험 성적서 수령', completed: false, dueDate: '2026-10-25' },
      { id: 't2-3', title: '인허가 신청서 온라인 제출 및 수수료 납부', completed: false, dueDate: '2026-10-30' },
      { id: 't2-4', title: '심사 보완요청 대응 및 최종 허가증 수령', completed: false, dueDate: '2026-11-15' },
    ],
    logs: [
      {
        id: 'log-2-1',
        date: '2026-10-06',
        category: 'meeting',
        content: 'RA 담당자 및 연구소 합동 사전 검토 회의 완료, 시험 성적서 일정 조율',
        author: '나',
      },
    ],
    createdAt: '2026-10-04T10:00:00.000Z',
    updatedAt: '2026-10-06T15:30:00.000Z',
  },
  {
    id: 'proj-3',
    title: '제조 공정 품질관리(QC/QA) 및 정기 심사 수검',
    description: '생산 라인 공정 불량률 저감 대책 수립 및 품질경영시스템 정기 사후심사 준비',
    category: '품질관리',
    priority: 'medium',
    status: 'completed',
    startDate: '2026-09-15',
    endDate: '2026-09-30',
    autoCalculateProgress: true,
    manualProgress: 100,
    tags: ['품질관리', 'QA', 'QC', 'ISO심사'],
    tasks: [
      { id: 't3-1', title: '원자재 수입 검사 기준서 및 시험방법 개정', completed: true, dueDate: '2026-09-18' },
      { id: 't3-2', title: '생산라인 모니터링 체크시트 점검 및 부적합 조치', completed: true, dueDate: '2026-09-24' },
      { id: 't3-3', title: '정기 품질 감사 보고서 작성 및 최종 승인', completed: true, dueDate: '2026-09-30' },
    ],
    logs: [
      {
        id: 'log-3-1',
        date: '2026-09-30',
        category: 'decision',
        content: '사후 심사 적합 판정 완료. 공정 불량률 전월 대비 15% 개선 확인!',
        author: '나',
      },
    ],
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-09-30T18:00:00.000Z',
  },
];
