import type { Project } from '../types/project';

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: '모바일 반응형 업무 관리 웹앱 출시',
    description: '어디서나 접속하여 프로젝트 진척도와 업무 일지를 실시간 관리하는 웹 대시보드 구축 및 Netlify 배포',
    category: '개발',
    priority: 'urgent',
    status: 'in-progress',
    startDate: '2026-10-01',
    endDate: '2026-10-15',
    autoCalculateProgress: true,
    manualProgress: 60,
    tags: ['React', 'Vite', 'Netlify', 'Tailwind'],
    tasks: [
      { id: 't1-1', title: '요구사항 정의 및 아키텍처 설계', completed: true, dueDate: '2026-10-03' },
      { id: 't1-2', title: 'React + TypeScript + Tailwind 환경 셋업', completed: true, dueDate: '2026-10-05' },
      { id: 't1-3', title: '대시보드 통계 및 프로젝트 카드 컴포넌트 개발', completed: true, dueDate: '2026-10-08' },
      { id: 't1-4', title: '칸반 보드 및 타임라인 간트 뷰 구현', completed: false, dueDate: '2026-10-11' },
      { id: 't1-5', title: '업무 일지 기록 및 실시간 진척도 연동', completed: false, dueDate: '2026-10-13' },
      { id: 't1-6', title: 'GitHub 저장소 푸시 및 Netlify 배포 완료', completed: false, dueDate: '2026-10-15' },
    ],
    logs: [
      {
        id: 'log-1-1',
        date: '2026-10-02',
        category: 'meeting',
        content: '프로젝트 범위 확정: 반응형 모바일 지원, 칸반 및 타임라인 뷰 제공 결정',
        author: '나',
      },
      {
        id: 'log-1-2',
        date: '2026-10-05',
        category: 'progress',
        content: 'Vite 기반 React 프로젝트 셋업 완료 및 Tailwind 디자인 시스템 적용 완료',
        author: '나',
      },
      {
        id: 'log-1-3',
        date: '2026-10-07',
        category: 'note',
        content: '로컬 스토리지 자동 저장 및 JSON 백업/복원 기능 추가 완료',
        author: '나',
      },
    ],
    createdAt: '2026-10-01T09:00:00.000Z',
    updatedAt: '2026-10-07T11:00:00.000Z',
  },
  {
    id: 'proj-2',
    title: '4분기 디지털 마케팅 전략 수립',
    description: 'SNS 채널별 유입 경로 분석 및 신규 고객 유치를 위한 프로모션 기획안 작성',
    category: '마케팅',
    priority: 'high',
    status: 'planned',
    startDate: '2026-10-10',
    endDate: '2026-10-25',
    autoCalculateProgress: true,
    manualProgress: 0,
    tags: ['마케팅', 'SNS', '광고기획'],
    tasks: [
      { id: 't2-1', title: '3분기 광고 성과 데이터 취합 및 분석', completed: true, dueDate: '2026-10-12' },
      { id: 't2-2', title: '타깃 고객 페르소나 정의 및 핵심 소구점 도출', completed: false, dueDate: '2026-10-16' },
      { id: 't2-3', title: '콘텐츠 제작 예산안 및 크리에이티브 시안 검토', completed: false, dueDate: '2026-10-20' },
      { id: 't2-4', title: '최종 보고서 작성 및 임원 보고', completed: false, dueDate: '2026-10-25' },
    ],
    logs: [
      {
        id: 'log-2-1',
        date: '2026-10-06',
        category: 'meeting',
        content: '디자인팀과 4분기 프로모션 비주얼 컨셉 킥오프 미팅 완료',
        author: '나',
      },
    ],
    createdAt: '2026-10-04T10:00:00.000Z',
    updatedAt: '2026-10-06T15:30:00.000Z',
  },
  {
    id: 'proj-3',
    title: '사내 업무 자동화 봇 스크립트 제작',
    description: '매일 반복되는 일일 리포트 작성 및 슬랙 알림 발송 파이썬 스크립트 구축',
    category: '기획',
    priority: 'medium',
    status: 'completed',
    startDate: '2026-09-15',
    endDate: '2026-09-30',
    autoCalculateProgress: true,
    manualProgress: 100,
    tags: ['자동화', 'Python', '업무효율화'],
    tasks: [
      { id: 't3-1', title: '반복 업무 프로세스 식별 및 API 명세 정리', completed: true, dueDate: '2026-09-18' },
      { id: 't3-2', title: '스크립트 작성 및 샌드박스 테스트', completed: true, dueDate: '2026-09-24' },
      { id: 't3-3', title: '스케줄러 등록 및 1주일 모니터링', completed: true, dueDate: '2026-09-30' },
    ],
    logs: [
      {
        id: 'log-3-1',
        date: '2026-09-30',
        category: 'decision',
        content: '자동화 배포 완료 후 매일 30분 소요되던 작업이 10초로 단축됨. 성공적 종료!',
        author: '나',
      },
    ],
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-09-30T18:00:00.000Z',
  },
];
